# Generated by Django 3.2.7 on 2021-10-21 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=50, verbose_name='categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('unidadMedida', models.CharField(max_length=50, verbose_name='unidadMedida')),
                ('stock', models.IntegerField(max_length=50, verbose_name='stock')),
                ('idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idCategoria', to='authApp.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('tel', models.CharField(max_length=30, verbose_name='tel')),
                ('ciudad', models.CharField(max_length=40, verbose_name='ciudad')),
                ('correo', models.EmailField(max_length=40, verbose_name='correo')),
            ],
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.AddField(
            model_name='producto',
            name='idProveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idProveedor', to='authApp.proveedor'),
        ),
    ]
